name: Sim-Only Conda CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest]
        python:
          - python-version: "3.7"
            pyVer: python3
          - python-version: "2.7"
            pyVer: python2

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Conda
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        channels: conda-forge,defaults
        mamba-version: "*"
        python-version: ${{ matrix.python.python-version }}
        environment-file: conda_env.yaml
        activate-environment: crazyswarm

    - name: Build
      shell: bash -l {0}
      run: |
        CSW_PYTHON=${{ matrix.python.pyVer }} ./buildSimOnly.sh

    - name: Test
      shell: bash -l {0}
      run: |
        cd ros_ws/src/crazyswarm/scripts
        python -m pytest
